[tool.poetry]
name = "borsh-construct"
version = "0.1.0"
description = "Python implementation of Borsh serialization, built on the Construct library."
authors = ["kevinheavey <kevinheavey123@gmail.com>"]
license = "MIT"
homepage = "https://github.com/near/borsh-construct-py"
repository = "https://github.com/near/borsh-construct-py"
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.8.3"
construct-typing = "^0.5.1"
sumtypes = "^0.1a5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
wemake-python-styleguide = "^0.15.3"
mypy = "^0.910"
black = "^21.7b0"
pydocstyle = "^6.1.1"
isort = "^5.9.3"
coverage = {extras = ["toml"], version = "^5.5"}
pytest-cov = "^2.12.1"
mkdocs = "^1.2.2"
mkdocs-material = "^7.2.6"
flake8 = "^3.9.2"
pytest-flake8 = "^1.0.7"
pytest-mypy = "^0.8.1"
hypothesis = "^6.23.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["borsh_construct"]

[tool.coverage.report]
show_missing = true
fail_under = 100
